# Pour un environnemnt Apache/Mysql/php/phpmyadmin
# site en local dans le répertoire www
# base de données local donc persistence des données

# Mon container SQL
mysql:
  image: mysql:5.7
  environment:
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: dbpassword
    MYSQL_ROOT_PASSWORD: dbrootpassword
    MYSQL_DATABASE: dbdatabase
  volumes_from:
    - datastore
  container_name: rad_mysql
# Mon container PHPMYADMIN
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
  ports:
    - '8080:80'
  container_name: rad_phpmyadmin
# Mon container central de stockage
datastore:
  image: busybox
  volumes:
    - /var/lib/mysql
  container_name: rad_store
# Mon container php basé sur l'image app du répertoire app
php:
  build: app
  ports:
    - '80:80'
  links:
    - mysql
  volumes:
    - ./www:/var/www/site
  container_name: rad_apache

